% ------------------------------------------------------------------------
% file `C++Primer_en-exercises-67-exercise-body.tex'
%
%     exercise of type `exercises' with id `67'
%
% generated by the `exercises' environment of the
%   `xsim' package v0.8a (2017/05/19)
% from source `C++Primer_en' on 2018/03/09 on line 10507
% ------------------------------------------------------------------------
\begin{question}
Write a program that reads two integers from the standard
input and prints the result of dividing the first number by the second.
\end{question}

\begin{question}
Revise your program to throw an exception if the second
number is zero. Test your program with a zero input to see what happens on
your system if you donâ€™t \verb|catch| an exception.
\end{question}

\begin{question}
Revise your program from the previous exercise to use a
\verb|try| block to \verb|catch| the exception. The \verb|catch| clause should print a message
to the user and ask them to supply a new number and repeat the code inside
the \verb|try|.
\end{question}
